spring.application.name=sba301-ecommerce

# ===== DataSource (SQL Server / MariaDB) =====
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;DatabaseName=sba301_ecommerce;encrypt=true;trustServerCertificate=true;}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.SQLServerDialect}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===== Server =====
server.port=8080
server.servlet.context-path=/api/v1

# ===== Springdoc / Swagger UI =====
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# ===== Actuator (dev) =====
management.endpoints.web.exposure.include=health,info

# ===== Custom app config =====
# Được cung cấp qua biến môi trường (e.g. export APP_JWT_SECRET=...)
app.jwt.secret=${APP_JWT_SECRET:}
app.jwt.expiration-ms=86400000

# ===== VNPay config =====
vnpay.tmn-code=OWBZLJR8
vnpay.hash-secret=OOV71FUQL5VBFDON8N90WFPOEJK5OO0V

# ===== Custom email config =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:group1projecthms@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:isie qifk ciyn lhiu}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===== CORS Configuration =====
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}

